name: ckb_localizations
description: "Support for kurdish sorani language ckb"
version: 0.1.0
homepage: https://github.com/masreplay/ckb_localizations

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

scripts:
  publish: dart pub publish --force
  fix-format: dart fix --apply && dart format -o write ./lib

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
